-- clickhouse-seed.sql
-- CSV로 저장된 기존 이벤트 데이터를 새 events 스키마에 맞춰 insert한다.

INSERT INTO events
(
    project_id,
    event_id,
    user_id,
    session_id,
    event_time,
    event_name,
    channel,
    campaign_id,
    age_group,
    gender,
    device,
    category,
    product_id,
    inventory_status,
    price,
    quantity,
    revenue,
    coupon_id,
    order_id,
    experiment_id,
    variant_id,
    action_id,
    mapping_id,
    ad_id,
    creative_id,
    properties_json,
    ingested_at
)
SELECT
    project_id,
    event_id,
    user_id,
    session_id,
    parseDateTime64BestEffort(event_time, 3, 'Asia/Seoul') AS event_time,
    event_name,
    channel,
    campaign_id,
    age_group,
    gender,
    device,
    category,
    product_id,
    inventory_status,
    toDecimal64OrDefault(price, 2) AS price,
    toUInt32OrZero(quantity) AS quantity,
    toDecimal64OrDefault(revenue, 2) AS revenue,
    coupon_id,
    order_id,
    '' AS experiment_id,
    '' AS variant_id,
    '' AS action_id,
    '' AS mapping_id,
    '' AS ad_id,
    '' AS creative_id,
    '{}' AS properties_json,
    now64(3, 'Asia/Seoul') AS ingested_at
FROM file(
    'ga4_exports/ga4_events_*.csv',
    'CSVWithNames',
    'project_id String, event_id String, user_id String, session_id String, event_time String, event_name String, channel String, campaign_id String, age_group String, gender String, device String, category String, product_id String, inventory_status String, price String, quantity String, revenue String, coupon_id String, order_id String'
);
