ANALYSIS_JOB_STATUS_QUEUED = "queued"
ANALYSIS_JOB_STATUS_RUNNING = "running"
ANALYSIS_JOB_STATUS_DONE = "done"
ANALYSIS_JOB_STATUS_FAILED = "failed"

ANALYSIS_JOB_STATUSES = {
    ANALYSIS_JOB_STATUS_QUEUED,
    ANALYSIS_JOB_STATUS_RUNNING,
    ANALYSIS_JOB_STATUS_DONE,
    ANALYSIS_JOB_STATUS_FAILED,
}
